/**
 * @file shell-env.js
 * @description Exposes API keys as shell environment variables via a sourced dotfile.
 *
 * @details
 *   Creates `~/.free-coding-models.env` containing `export VAR="value"` lines for every
 *   configured provider, and injects a single `[ -f ~/.free-coding-models.env ] && source ...`
 *   line into the user's shell rc file (`.zshrc`, `.bashrc`, or fish `config.fish`).
 *
 *   The env file is kept in sync automatically: every time `saveConfig()` or
 *   `persistApiKeysForProvider()` writes a new config to disk, `syncShellEnv()` is called
 *   to regenerate the `.env` if `settings.shellEnvEnabled === true`.
 *
 *   Shell detection uses `$SHELL` with a fallback chain: zsh → bash → fish.
 *   Each shell's rc path is resolved relative to `$HOME`. Fish uses `set -gx` syntax
 *   instead of `export`, which is handled transparently.
 *
 *   The env file is written with mode `0600` (owner read/write only) to protect API keys.
 *   The source line in the rc file is idempotent — calling `ensureShellRcSource()` multiple
 *   times will never add a duplicate line.
 *
 * @functions
 *   → `syncShellEnv(config)` — regenerate the .env file from current apiKeys
 *   → `ensureShellRcSource()` — add the source line to the detected shell rc (idempotent)
 *   → `removeShellEnv()` — delete the .env file and remove the source line from rc
 *   → `detectShellInfo()` — return { shell, rcPath } for the current user
 *   → `getEnvFilePath()` — return the absolute path to ~/.free-coding-models.env
 *   → `buildEnvContent(config, shell)` — build the env file body (pure function, testable)
 *   → `buildRcSourceLine(envFilePath, shell)` — build the rc source line for a given shell
 *
 * @exports syncShellEnv, ensureShellRcSource, removeShellEnv, detectShellInfo,
 *          getEnvFilePath, buildEnvContent, buildRcSourceLine, ENV_FILE_MARKER
 *
 * @see src/config.js — calls syncShellEnv() after saveConfig()
 * @see src/provider-metadata.js — ENV_VAR_NAMES maps provider → env var name
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync, unlinkSync } from 'node:fs'
import { homedir } from 'node:os'
import { join } from 'node:path'
import * as readline from 'node:readline'
import chalk from 'chalk'
import { ENV_VAR_NAMES } from './provider-metadata.js'
import { saveConfig } from './config.js'

// 📖 Unique marker used to identify the source line we inject into shell rc files.
// 📖 This allows idempotent add/remove without relying on exact path matching.
export const ENV_FILE_MARKER = '# free-coding-models-env'

// 📖 The env dotfile path — always next to the JSON config in $HOME.
const ENV_FILE_NAME = '.free-coding-models.env'

/**
 * 📖 Returns the absolute path to the env dotfile.
 * @returns {string}
 */
export function getEnvFilePath() {
  return join(homedir(), ENV_FILE_NAME)
}

/**
 * 📖 Detect the user's shell and return its rc file path.
 *
 * Detection order: $SHELL env var → fallback to zsh → bash → fish.
 * Returns the shell type ('zsh'|'bash'|'fish') and the absolute rc path.
 *
 * @returns {{ shell: 'zsh'|'bash'|'fish', rcPath: string }}
 */
export function detectShellInfo() {
  const shellEnv = (process.env.SHELL || '').toLowerCase()
  const home = homedir()

  if (shellEnv.includes('zsh')) {
    return { shell: 'zsh', rcPath: join(home, '.zshrc') }
  }
  if (shellEnv.includes('bash')) {
    return { shell: 'bash', rcPath: join(home, '.bashrc') }
  }
  if (shellEnv.includes('fish')) {
    return { shell: 'fish', rcPath: join(home, '.config', 'fish', 'config.fish') }
  }

  // 📖 Fallback: try to detect which rc files exist
  if (existsSync(join(home, '.zshrc'))) {
    return { shell: 'zsh', rcPath: join(home, '.zshrc') }
  }
  if (existsSync(join(home, '.bashrc'))) {
    return { shell: 'bash', rcPath: join(home, '.bashrc') }
  }
  const fishConfig = join(home, '.config', 'fish', 'config.fish')
  if (existsSync(fishConfig)) {
    return { shell: 'fish', rcPath: fishConfig }
  }

  // 📖 Last resort: assume zsh (most common on macOS/Linux)
  return { shell: 'zsh', rcPath: join(home, '.zshrc') }
}

/**
 * 📖 Build the env file content for a given shell type.
 *
 * Pure function — no I/O. Iterates over config.apiKeys and generates
 * the appropriate `export` (bash/zsh) or `set -gx` (fish) lines.
 *
 * @param {{ apiKeys: Record<string, string|string[]> }} config
 * @param {'zsh'|'bash'|'fish'} shell
 * @returns {string} The complete file content to write
 */
export function buildEnvContent(config, shell) {
  const apiKeys = config?.apiKeys || {}
  const lines = [
    '#!/bin/env sh',
    `# ${ENV_FILE_MARKER}`,
    '# Auto-generated by free-coding-models — do not edit manually.',
    '# Changes to API keys are synced automatically from the TUI.',
    '',
  ]

  const isFish = shell === 'fish'

  for (const [providerKey, envName] of Object.entries(ENV_VAR_NAMES)) {
    const rawValue = apiKeys[providerKey]
    if (!rawValue) continue

    // 📖 Support multi-key arrays — use the first key for shell env
    const value = Array.isArray(rawValue) ? rawValue[0] : rawValue
    if (!value || typeof value !== 'string') continue

    const safeValue = value.replace(/'/g, "'\\''")

    if (isFish) {
      lines.push(`set -gx ${envName} '${safeValue}'`)
    } else {
      lines.push(`export ${envName}='${safeValue}'`)
    }
  }

  lines.push('')
  return lines.join('\n')
}

/**
 * 📖 Build the rc source line that loads the env file.
 *
 * For bash/zsh: `[ -f ~/.free-coding-models.env ] && . ~/.free-coding-models.env  # free-coding-models-env`
 * For fish:     `test -f ~/.free-coding-models.env; and source ~/.free-coding-models.env  # free-coding-models-env`
 *
 * @param {string} envFilePath — absolute path to the .env file
 * @param {'zsh'|'bash'|'fish'} shell
 * @returns {string} A single line to append to the rc file
 */
export function buildRcSourceLine(envFilePath, shell) {
  const home = homedir()
  // 📖 Use ~/ relative path in rc for portability
  const relativePath = envFilePath.startsWith(home)
    ? '~/' + envFilePath.slice(home.length + 1)
    : envFilePath

  if (shell === 'fish') {
    return `test -f ${relativePath}; and source ${relativePath}  ${ENV_FILE_MARKER}`
  }
  return `[ -f ${relativePath} ] && . ${relativePath}  ${ENV_FILE_MARKER}`
}

/**
 * 📖 Regenerate the env file from the current config.
 *
 * Called after every saveConfig() when shellEnvEnabled is true.
 * Writes with mode 0600 for security. Skips if there are no keys.
 *
 * @param {{ apiKeys: Record<string, string|string[]>, settings?: { shellEnvEnabled?: boolean } }} config
 * @returns {{ success: boolean, envPath: string, error?: string }}
 */
export function syncShellEnv(config) {
  const { shell } = detectShellInfo()
  const envPath = getEnvFilePath()
  const apiKeys = config?.apiKeys || {}
  const hasKeys = Object.values(apiKeys).some(v => {
    if (Array.isArray(v)) return v.length > 0
    return !!v
  })

  if (!hasKeys) {
    // 📖 No keys — remove stale env file if it exists
    if (existsSync(envPath)) {
      try { unlinkSync(envPath) } catch { /* best effort */ }
    }
    return { success: true, envPath }
  }

  try {
    const content = buildEnvContent(config, shell)
    writeFileSync(envPath, content, { mode: 0o600 })
    return { success: true, envPath }
  } catch (err) {
    return { success: false, envPath, error: err.message }
  }
}

/**
 * 📖 Add the source line to the user's shell rc file (idempotent).
 *
 * Creates the rc file if it doesn't exist. Skips if the marker is already present.
 *
 * @returns {{ success: boolean, rcPath: string, wasAdded: boolean, error?: string }}
 */
export function ensureShellRcSource() {
  const { shell, rcPath } = detectShellInfo()
  const envPath = getEnvFilePath()
  const sourceLine = buildRcSourceLine(envPath, shell)

  let existingContent = ''
  if (existsSync(rcPath)) {
    try {
      existingContent = readFileSync(rcPath, 'utf8')
    } catch (err) {
      return { success: false, rcPath, wasAdded: false, error: `Cannot read ${rcPath}: ${err.message}` }
    }
  }

  // 📖 Idempotent: skip if our marker is already in the file
  if (existingContent.includes(ENV_FILE_MARKER)) {
    return { success: true, rcPath, wasAdded: false }
  }

  try {
    // 📖 Ensure parent directory exists (e.g. ~/.config/fish/)
    const dir = join(rcPath, '..')
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true })

    const newContent = existingContent
      ? existingContent.trimEnd() + '\n\n' + sourceLine + '\n'
      : sourceLine + '\n'
    writeFileSync(rcPath, newContent)
    return { success: true, rcPath, wasAdded: true }
  } catch (err) {
    return { success: false, rcPath, wasAdded: false, error: `Cannot write ${rcPath}: ${err.message}` }
  }
}

/**
 * 📖 Remove the env file and the source line from the shell rc.
 *
 * @returns {{ success: boolean, envRemoved: boolean, rcCleaned: boolean, error?: string }}
 */
export function removeShellEnv() {
  const { shell, rcPath } = detectShellInfo()
  const envPath = getEnvFilePath()
  let envRemoved = false
  let rcCleaned = false

  // 📖 Remove the env file
  if (existsSync(envPath)) {
    try {
      unlinkSync(envPath)
      envRemoved = true
    } catch (err) {
      return { success: false, envRemoved: false, rcCleaned: false, error: `Cannot delete ${envPath}: ${err.message}` }
    }
  }

  // 📖 Remove the source line from rc
  if (existsSync(rcPath)) {
    try {
      const content = readFileSync(rcPath, 'utf8')
      if (content.includes(ENV_FILE_MARKER)) {
        const cleaned = content
          .split('\n')
          .filter(line => !line.includes(ENV_FILE_MARKER))
          .join('\n')
          .replace(/\n{3,}/g, '\n\n')
        writeFileSync(rcPath, cleaned)
        rcCleaned = true
      }
    } catch {
      // 📖 Non-critical — env file is already removed
    }
  }

  return { success: true, envRemoved, rcCleaned }
}

/**
 * 📖 Pre-TUI popup asking the user whether to enable shell env exposure.
 *
 * Follows the same pattern as `promptUpdateNotification()` in updater.js.
 * Shows three options: Enable (recommended, green), Skip for now, Don't ask again.
 * Runs BEFORE entering the alt-screen buffer so it renders in the normal terminal.
 *
 * @param {{ apiKeys: Record<string, string|string[]>, settings: object }} config
 * @returns {Promise<'enable'|'skip'|'never'>} The user's choice
 */
export async function promptShellEnvMigration(config) {
  const { shell, rcPath } = detectShellInfo()
  const rcName = rcPath.split('/').pop()
  const keyCount = Object.keys(config.apiKeys || {}).filter(pk => {
    const v = config.apiKeys[pk]
    return Array.isArray(v) ? v.length > 0 : !!v
  }).length

  return new Promise((resolve) => {
    let selected = 0
    const options = [
      {
        label: 'Yes, enable (recommended)',
        icon: '✅',
        description: `Export ${keyCount} API key${keyCount > 1 ? 's' : ''} to shell via ${rcName}`,
      },
      {
        label: 'Skip for now',
        icon: '⏭',
        description: 'You can enable it later in Settings (P)',
      },
      {
        label: "Don't ask again",
        icon: '🔇',
        description: 'Disable this prompt permanently',
      },
    ]

    const render = () => {
      process.stdout.write('\x1b[2J\x1b[H')

      const terminalWidth = process.stdout.columns || 80
      const maxWidth = Math.min(terminalWidth - 4, 70)
      const centerPad = ' '.repeat(Math.max(0, Math.floor((terminalWidth - maxWidth) / 2)))

      console.log()
      console.log(centerPad + chalk.bold.rgb(110, 214, 255)('  🐚 Shell Environment Setup'))
      console.log()
      console.log(centerPad + chalk.white('  Expose your API keys as environment variables'))
      console.log(centerPad + chalk.white('  so they are available globally in your shell.'))
      console.log()
      console.log(centerPad + chalk.dim(`  Detected shell: ${shell} (${rcName})`))
      console.log(centerPad + chalk.dim(`  This adds a single source line to ${rcName}`))
      console.log(centerPad + chalk.dim('  and creates ~/.free-coding-models.env (0600)'))
      console.log()

      for (let i = 0; i < options.length; i++) {
        const isSelected = i === selected
        const bullet = isSelected ? chalk.bold.cyan('  ❯ ') : chalk.dim('    ')
        let label
        if (i === 0) {
          label = isSelected
            ? chalk.bold.rgb(112, 231, 181)(options[i].icon + ' ' + options[i].label + ' ★')
            : chalk.rgb(112, 231, 181)(options[i].icon + ' ' + options[i].label)
        } else {
          label = isSelected
            ? chalk.bold.white(options[i].icon + ' ' + options[i].label)
            : chalk.dim(options[i].icon + ' ' + options[i].label)
        }

        console.log(centerPad + bullet + label)
        console.log(centerPad + chalk.dim('       ' + options[i].description))
        console.log()
      }

      console.log(centerPad + chalk.dim('  ↑↓ Navigate  •  Enter Select  •  Ctrl+C Skip'))
      console.log()
    }

    render()

    readline.emitKeypressEvents(process.stdin)
    // 📖 Ensure stdin is flowing — a prior prompt may have paused it
    process.stdin.resume()
    if (process.stdin.isTTY) process.stdin.setRawMode(true)

    const onKey = (_str, key) => {
      if (!key) return
      if (key.ctrl && key.name === 'c') {
        if (process.stdin.isTTY) process.stdin.setRawMode(false)
        process.stdin.removeListener('keypress', onKey)
        // 📖 User chose to skip — record this so the prompt never shows again on restart
        if (!config.settings) config.settings = {}
        config.settings.shellEnvEnabled = false
        saveConfig(config)
        resolve('skip')
        return
      }
      if (key.name === 'up' && selected > 0) {
        selected--
        render()
      } else if (key.name === 'down' && selected < options.length - 1) {
        selected++
        render()
      } else if (key.name === 'return') {
        if (process.stdin.isTTY) process.stdin.setRawMode(false)
        process.stdin.removeListener('keypress', onKey)
        process.stdin.pause()

        if (selected === 0) resolve('enable')
        else if (selected === 1) resolve('skip')
        else resolve('never')
      }
    }

    process.stdin.on('keypress', onKey)
  })
}
